[package]
name = "parse-forbes-50"
version = "0.1.0"
authors = ["Vipin Bharathan <vipinsun@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1.3"
serde = { version = "1.0.104", features = ["derive"] }
serde_derive="1.0.104"
nom = "5.1.1"