[package]
name = "parse-forbes-50"
version = "0.1.0"
authors = ["Vipin Bharathan <vipinsun@gmail.com>"]
edition="2018"

[dependencies]
csv = "1.1.5"
regex = "1.4.3"
serde = { version = "1.0.123", features = ["derive"] }
serde_derive="1.0.123"
nom = "6.1.0"